# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env_files:
        github_token: ~/.config/goreleaser/github_token
builds:
- main: cmd/go-aes/main.go
  id: go-aes
  binary: go-aes
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  - netbsd
  - openbsd
  - plan9  
  goarch:
  - amd64
  - 386
  - arm
  - arm64
- main: cmd/genkey/main.go
  id: go-aes-genkey
  binary: go-eas-genkey
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  - netbsd
  - openbsd
  - plan9  
  goarch:
  - amd64
  - 386
  - arm
  - arm64
  env:
  - CGO_ENABLED=0
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
